#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.net___Enrollment_System
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="login_db")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStud_info(Stud_info instance);
    partial void UpdateStud_info(Stud_info instance);
    partial void DeleteStud_info(Stud_info instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ASP.net___Enrollment_System.Properties.Settings.Default.login_dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<login_info> login_infos
		{
			get
			{
				return this.GetTable<login_info>();
			}
		}
		
		public System.Data.Linq.Table<Stud_info> Stud_infos
		{
			get
			{
				return this.GetTable<Stud_info>();
			}
		}
		
		public System.Data.Linq.Table<Section_info> Section_infos
		{
			get
			{
				return this.GetTable<Section_info>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_login")]
		public ISingleResult<pro_loginResult> pro_login([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password);
			return ((ISingleResult<pro_loginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.check_section")]
		public ISingleResult<check_sectionResult> check_section([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string course, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string year)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), course, year);
			return ((ISingleResult<check_sectionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.add_capacity")]
		public int add_capacity([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string course, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string year)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), course, year);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checksectionname")]
		public ISingleResult<checksectionnameResult> checksectionname([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string course, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string year, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string section)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), course, year, section);
			return ((ISingleResult<checksectionnameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addnewsection")]
		public int addnewsection([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string course, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string year, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string section, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maxcapacity)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), course, year, section, maxcapacity);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.enroll_student")]
		public int enroll_student([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fname", DbType="VarChar(50)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lname", DbType="VarChar(50)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mname", DbType="VarChar(50)")] string mname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sname", DbType="VarChar(50)")] string sname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(50)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bday", DbType="Date")] System.Nullable<System.DateTime> bday, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LRN", DbType="BigInt")] System.Nullable<long> lRN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="VarChar(50)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pnum", DbType="BigInt")] System.Nullable<long> pnum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Course", DbType="VarChar(50)")] string course, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Year", DbType="VarChar(50)")] string year)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fname, lname, mname, sname, gender, bday, lRN, address, pnum, email, course, year);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.studentlist")]
		public ISingleResult<studentlistResult> studentlist()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<studentlistResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.searchstudent")]
		public ISingleResult<searchstudentResult> searchstudent([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string temp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), temp);
			return ((ISingleResult<searchstudentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sectionlist")]
		public ISingleResult<sectionlistResult> sectionlist()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sectionlistResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sectionsearch")]
		public ISingleResult<sectionsearchResult> sectionsearch([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string course, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string year)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), course, year);
			return ((ISingleResult<sectionsearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.changepass")]
		public int changepass([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.loginuser")]
		public ISingleResult<loginuserResult> loginuser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username);
			return ((ISingleResult<loginuserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checkusertype")]
		public ISingleResult<checkusertypeResult> checkusertype([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username);
			return ((ISingleResult<checkusertypeResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.login_info")]
	public partial class login_info
	{
		
		private int _id;
		
		private string _Fname;
		
		private string _Lname;
		
		private string _Username;
		
		private string _passwords;
		
		private System.Nullable<int> _usertype;
		
		public login_info()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50)")]
		public string Fname
		{
			get
			{
				return this._Fname;
			}
			set
			{
				if ((this._Fname != value))
				{
					this._Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50)")]
		public string Lname
		{
			get
			{
				return this._Lname;
			}
			set
			{
				if ((this._Lname != value))
				{
					this._Lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passwords", DbType="VarChar(50)")]
		public string passwords
		{
			get
			{
				return this._passwords;
			}
			set
			{
				if ((this._passwords != value))
				{
					this._passwords = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usertype", DbType="Int")]
		public System.Nullable<int> usertype
		{
			get
			{
				return this._usertype;
			}
			set
			{
				if ((this._usertype != value))
				{
					this._usertype = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stud_info")]
	public partial class Stud_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _Stud_ID;
		
		private string _Stud_Fname;
		
		private string _Stud_Lname;
		
		private string _Stud_Mname;
		
		private string _Stud_Sname;
		
		private string _Stud_Gender;
		
		private System.Nullable<System.DateTime> _Stud_Bday;
		
		private System.Nullable<long> _Stud_LRN;
		
		private string _Stud_Address;
		
		private System.Nullable<long> _Stud_Pnumber;
		
		private string _Stud_Email;
		
		private string _Stud_Course;
		
		private string _Stud_Year;
		
		private string _Stud_Section;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnStud_IDChanging(int value);
    partial void OnStud_IDChanged();
    partial void OnStud_FnameChanging(string value);
    partial void OnStud_FnameChanged();
    partial void OnStud_LnameChanging(string value);
    partial void OnStud_LnameChanged();
    partial void OnStud_MnameChanging(string value);
    partial void OnStud_MnameChanged();
    partial void OnStud_SnameChanging(string value);
    partial void OnStud_SnameChanged();
    partial void OnStud_GenderChanging(string value);
    partial void OnStud_GenderChanged();
    partial void OnStud_BdayChanging(System.Nullable<System.DateTime> value);
    partial void OnStud_BdayChanged();
    partial void OnStud_LRNChanging(System.Nullable<long> value);
    partial void OnStud_LRNChanged();
    partial void OnStud_AddressChanging(string value);
    partial void OnStud_AddressChanged();
    partial void OnStud_PnumberChanging(System.Nullable<long> value);
    partial void OnStud_PnumberChanged();
    partial void OnStud_EmailChanging(string value);
    partial void OnStud_EmailChanged();
    partial void OnStud_CourseChanging(string value);
    partial void OnStud_CourseChanged();
    partial void OnStud_YearChanging(string value);
    partial void OnStud_YearChanged();
    partial void OnStud_SectionChanging(string value);
    partial void OnStud_SectionChanged();
    #endregion
		
		public Stud_info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_ID", DbType="Int NOT NULL")]
		public int Stud_ID
		{
			get
			{
				return this._Stud_ID;
			}
			set
			{
				if ((this._Stud_ID != value))
				{
					this.OnStud_IDChanging(value);
					this.SendPropertyChanging();
					this._Stud_ID = value;
					this.SendPropertyChanged("Stud_ID");
					this.OnStud_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_Fname", DbType="VarChar(50)")]
		public string Stud_Fname
		{
			get
			{
				return this._Stud_Fname;
			}
			set
			{
				if ((this._Stud_Fname != value))
				{
					this.OnStud_FnameChanging(value);
					this.SendPropertyChanging();
					this._Stud_Fname = value;
					this.SendPropertyChanged("Stud_Fname");
					this.OnStud_FnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_Lname", DbType="VarChar(50)")]
		public string Stud_Lname
		{
			get
			{
				return this._Stud_Lname;
			}
			set
			{
				if ((this._Stud_Lname != value))
				{
					this.OnStud_LnameChanging(value);
					this.SendPropertyChanging();
					this._Stud_Lname = value;
					this.SendPropertyChanged("Stud_Lname");
					this.OnStud_LnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_Mname", DbType="VarChar(50)")]
		public string Stud_Mname
		{
			get
			{
				return this._Stud_Mname;
			}
			set
			{
				if ((this._Stud_Mname != value))
				{
					this.OnStud_MnameChanging(value);
					this.SendPropertyChanging();
					this._Stud_Mname = value;
					this.SendPropertyChanged("Stud_Mname");
					this.OnStud_MnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_Sname", DbType="VarChar(50)")]
		public string Stud_Sname
		{
			get
			{
				return this._Stud_Sname;
			}
			set
			{
				if ((this._Stud_Sname != value))
				{
					this.OnStud_SnameChanging(value);
					this.SendPropertyChanging();
					this._Stud_Sname = value;
					this.SendPropertyChanged("Stud_Sname");
					this.OnStud_SnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_Gender", DbType="VarChar(50)")]
		public string Stud_Gender
		{
			get
			{
				return this._Stud_Gender;
			}
			set
			{
				if ((this._Stud_Gender != value))
				{
					this.OnStud_GenderChanging(value);
					this.SendPropertyChanging();
					this._Stud_Gender = value;
					this.SendPropertyChanged("Stud_Gender");
					this.OnStud_GenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_Bday", DbType="Date")]
		public System.Nullable<System.DateTime> Stud_Bday
		{
			get
			{
				return this._Stud_Bday;
			}
			set
			{
				if ((this._Stud_Bday != value))
				{
					this.OnStud_BdayChanging(value);
					this.SendPropertyChanging();
					this._Stud_Bday = value;
					this.SendPropertyChanged("Stud_Bday");
					this.OnStud_BdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_LRN", DbType="BigInt")]
		public System.Nullable<long> Stud_LRN
		{
			get
			{
				return this._Stud_LRN;
			}
			set
			{
				if ((this._Stud_LRN != value))
				{
					this.OnStud_LRNChanging(value);
					this.SendPropertyChanging();
					this._Stud_LRN = value;
					this.SendPropertyChanged("Stud_LRN");
					this.OnStud_LRNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_Address", DbType="VarChar(50)")]
		public string Stud_Address
		{
			get
			{
				return this._Stud_Address;
			}
			set
			{
				if ((this._Stud_Address != value))
				{
					this.OnStud_AddressChanging(value);
					this.SendPropertyChanging();
					this._Stud_Address = value;
					this.SendPropertyChanged("Stud_Address");
					this.OnStud_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_Pnumber", DbType="BigInt")]
		public System.Nullable<long> Stud_Pnumber
		{
			get
			{
				return this._Stud_Pnumber;
			}
			set
			{
				if ((this._Stud_Pnumber != value))
				{
					this.OnStud_PnumberChanging(value);
					this.SendPropertyChanging();
					this._Stud_Pnumber = value;
					this.SendPropertyChanged("Stud_Pnumber");
					this.OnStud_PnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_Email", DbType="VarChar(50)")]
		public string Stud_Email
		{
			get
			{
				return this._Stud_Email;
			}
			set
			{
				if ((this._Stud_Email != value))
				{
					this.OnStud_EmailChanging(value);
					this.SendPropertyChanging();
					this._Stud_Email = value;
					this.SendPropertyChanged("Stud_Email");
					this.OnStud_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_Course", DbType="VarChar(50)")]
		public string Stud_Course
		{
			get
			{
				return this._Stud_Course;
			}
			set
			{
				if ((this._Stud_Course != value))
				{
					this.OnStud_CourseChanging(value);
					this.SendPropertyChanging();
					this._Stud_Course = value;
					this.SendPropertyChanged("Stud_Course");
					this.OnStud_CourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_Year", DbType="VarChar(50)")]
		public string Stud_Year
		{
			get
			{
				return this._Stud_Year;
			}
			set
			{
				if ((this._Stud_Year != value))
				{
					this.OnStud_YearChanging(value);
					this.SendPropertyChanging();
					this._Stud_Year = value;
					this.SendPropertyChanged("Stud_Year");
					this.OnStud_YearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_Section", DbType="VarChar(50)")]
		public string Stud_Section
		{
			get
			{
				return this._Stud_Section;
			}
			set
			{
				if ((this._Stud_Section != value))
				{
					this.OnStud_SectionChanging(value);
					this.SendPropertyChanging();
					this._Stud_Section = value;
					this.SendPropertyChanged("Stud_Section");
					this.OnStud_SectionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Section_info")]
	public partial class Section_info
	{
		
		private string _COURSE;
		
		private string _YR_LEVEL;
		
		private string _SECTION;
		
		private System.Nullable<int> _CAPACITY;
		
		private System.Nullable<int> _MAX_CAPACITY;
		
		public Section_info()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COURSE", DbType="VarChar(50)")]
		public string COURSE
		{
			get
			{
				return this._COURSE;
			}
			set
			{
				if ((this._COURSE != value))
				{
					this._COURSE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YR_LEVEL", DbType="VarChar(50)")]
		public string YR_LEVEL
		{
			get
			{
				return this._YR_LEVEL;
			}
			set
			{
				if ((this._YR_LEVEL != value))
				{
					this._YR_LEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTION", DbType="VarChar(50)")]
		public string SECTION
		{
			get
			{
				return this._SECTION;
			}
			set
			{
				if ((this._SECTION != value))
				{
					this._SECTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAPACITY", DbType="Int")]
		public System.Nullable<int> CAPACITY
		{
			get
			{
				return this._CAPACITY;
			}
			set
			{
				if ((this._CAPACITY != value))
				{
					this._CAPACITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAX_CAPACITY", DbType="Int")]
		public System.Nullable<int> MAX_CAPACITY
		{
			get
			{
				return this._MAX_CAPACITY;
			}
			set
			{
				if ((this._MAX_CAPACITY != value))
				{
					this._MAX_CAPACITY = value;
				}
			}
		}
	}
	
	public partial class pro_loginResult
	{
		
		private string _username;
		
		private string _passwords;
		
		private System.Nullable<int> _usertype;
		
		public pro_loginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passwords", DbType="VarChar(50)")]
		public string passwords
		{
			get
			{
				return this._passwords;
			}
			set
			{
				if ((this._passwords != value))
				{
					this._passwords = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usertype", DbType="Int")]
		public System.Nullable<int> usertype
		{
			get
			{
				return this._usertype;
			}
			set
			{
				if ((this._usertype != value))
				{
					this._usertype = value;
				}
			}
		}
	}
	
	public partial class check_sectionResult
	{
		
		private string _SECTION;
		
		public check_sectionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTION", DbType="VarChar(50)")]
		public string SECTION
		{
			get
			{
				return this._SECTION;
			}
			set
			{
				if ((this._SECTION != value))
				{
					this._SECTION = value;
				}
			}
		}
	}
	
	public partial class checksectionnameResult
	{
		
		private string _section;
		
		public checksectionnameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_section", DbType="VarChar(50)")]
		public string section
		{
			get
			{
				return this._section;
			}
			set
			{
				if ((this._section != value))
				{
					this._section = value;
				}
			}
		}
	}
	
	public partial class studentlistResult
	{
		
		private int _ID_Number;
		
		private string _Student_Name;
		
		private string _Student_Course;
		
		private string _Student_Year;
		
		private string _Student_Section;
		
		public studentlistResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ID Number]", Storage="_ID_Number", DbType="Int NOT NULL")]
		public int ID_Number
		{
			get
			{
				return this._ID_Number;
			}
			set
			{
				if ((this._ID_Number != value))
				{
					this._ID_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Student Name]", Storage="_Student_Name", DbType="VarChar(154)")]
		public string Student_Name
		{
			get
			{
				return this._Student_Name;
			}
			set
			{
				if ((this._Student_Name != value))
				{
					this._Student_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Student Course]", Storage="_Student_Course", DbType="VarChar(50)")]
		public string Student_Course
		{
			get
			{
				return this._Student_Course;
			}
			set
			{
				if ((this._Student_Course != value))
				{
					this._Student_Course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Student Year]", Storage="_Student_Year", DbType="VarChar(50)")]
		public string Student_Year
		{
			get
			{
				return this._Student_Year;
			}
			set
			{
				if ((this._Student_Year != value))
				{
					this._Student_Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Student Section]", Storage="_Student_Section", DbType="VarChar(50)")]
		public string Student_Section
		{
			get
			{
				return this._Student_Section;
			}
			set
			{
				if ((this._Student_Section != value))
				{
					this._Student_Section = value;
				}
			}
		}
	}
	
	public partial class searchstudentResult
	{
		
		private int _ID_Number;
		
		private string _Student_Name;
		
		private string _Student_Course;
		
		private string _Student_Year;
		
		private string _Student_Section;
		
		public searchstudentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ID Number]", Storage="_ID_Number", DbType="Int NOT NULL")]
		public int ID_Number
		{
			get
			{
				return this._ID_Number;
			}
			set
			{
				if ((this._ID_Number != value))
				{
					this._ID_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Student Name]", Storage="_Student_Name", DbType="VarChar(154)")]
		public string Student_Name
		{
			get
			{
				return this._Student_Name;
			}
			set
			{
				if ((this._Student_Name != value))
				{
					this._Student_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Student Course]", Storage="_Student_Course", DbType="VarChar(50)")]
		public string Student_Course
		{
			get
			{
				return this._Student_Course;
			}
			set
			{
				if ((this._Student_Course != value))
				{
					this._Student_Course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Student Year]", Storage="_Student_Year", DbType="VarChar(50)")]
		public string Student_Year
		{
			get
			{
				return this._Student_Year;
			}
			set
			{
				if ((this._Student_Year != value))
				{
					this._Student_Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Student Section]", Storage="_Student_Section", DbType="VarChar(50)")]
		public string Student_Section
		{
			get
			{
				return this._Student_Section;
			}
			set
			{
				if ((this._Student_Section != value))
				{
					this._Student_Section = value;
				}
			}
		}
	}
	
	public partial class sectionlistResult
	{
		
		private string _COURSE;
		
		private string _YEAR_LEVEL;
		
		private string _SECTION;
		
		private System.Nullable<int> _STUDENT_COUNT;
		
		public sectionlistResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COURSE", DbType="VarChar(50)")]
		public string COURSE
		{
			get
			{
				return this._COURSE;
			}
			set
			{
				if ((this._COURSE != value))
				{
					this._COURSE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR LEVEL]", Storage="_YEAR_LEVEL", DbType="VarChar(50)")]
		public string YEAR_LEVEL
		{
			get
			{
				return this._YEAR_LEVEL;
			}
			set
			{
				if ((this._YEAR_LEVEL != value))
				{
					this._YEAR_LEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTION", DbType="VarChar(50)")]
		public string SECTION
		{
			get
			{
				return this._SECTION;
			}
			set
			{
				if ((this._SECTION != value))
				{
					this._SECTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[STUDENT COUNT]", Storage="_STUDENT_COUNT", DbType="Int")]
		public System.Nullable<int> STUDENT_COUNT
		{
			get
			{
				return this._STUDENT_COUNT;
			}
			set
			{
				if ((this._STUDENT_COUNT != value))
				{
					this._STUDENT_COUNT = value;
				}
			}
		}
	}
	
	public partial class sectionsearchResult
	{
		
		private string _COURSE;
		
		private string _YEAR_LEVEL;
		
		private string _SECTION;
		
		private System.Nullable<int> _STUDENT_COUNT;
		
		public sectionsearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COURSE", DbType="VarChar(50)")]
		public string COURSE
		{
			get
			{
				return this._COURSE;
			}
			set
			{
				if ((this._COURSE != value))
				{
					this._COURSE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR LEVEL]", Storage="_YEAR_LEVEL", DbType="VarChar(50)")]
		public string YEAR_LEVEL
		{
			get
			{
				return this._YEAR_LEVEL;
			}
			set
			{
				if ((this._YEAR_LEVEL != value))
				{
					this._YEAR_LEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTION", DbType="VarChar(50)")]
		public string SECTION
		{
			get
			{
				return this._SECTION;
			}
			set
			{
				if ((this._SECTION != value))
				{
					this._SECTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[STUDENT COUNT]", Storage="_STUDENT_COUNT", DbType="Int")]
		public System.Nullable<int> STUDENT_COUNT
		{
			get
			{
				return this._STUDENT_COUNT;
			}
			set
			{
				if ((this._STUDENT_COUNT != value))
				{
					this._STUDENT_COUNT = value;
				}
			}
		}
	}
	
	public partial class loginuserResult
	{
		
		private string _Username;
		
		public loginuserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
	}
	
	public partial class checkusertypeResult
	{
		
		private System.Nullable<int> _usertype;
		
		public checkusertypeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usertype", DbType="Int")]
		public System.Nullable<int> usertype
		{
			get
			{
				return this._usertype;
			}
			set
			{
				if ((this._usertype != value))
				{
					this._usertype = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
